[Easy] update OWL token dependency
gnosis/dex-contracts pull request #1024
Opened 2020-10-20 12:40 UTC by bh2smith

The most recent release of OWL token changed the directory structure of the contracts folder (splitting the different solidity versions). Thus we had to adjust our import statements

2020-10-20 18:33 UTC, nlordell commented
Does this mean that the contracts need to be re-released?

2020-10-20 18:33 UTC, nlordell approved these changes

2020-10-20 19:22 UTC, fleupold approved these changes

2020-10-21 05:17 UTC, bh2smith commented
> Does this mean that the contracts need to be re-released?

In a sense, yes but I don’t consider it all that urgent. Could wait till next week or even longer. Unless, you think it might make sense to bump the version right here in this PR.

2020-10-21 05:56 UTC, nlordell requested changes
So, in checking the NPM module, it looks like we won't need to re-publish a new version after this version bump since it is only a dev-dependency.

However, I think:
- `@gnosis.pm/owl-token@3.2.0` needs to be yanked
- `@gnosis.pm/owl-token@4.0.0` needs to be published.

I think the decision to use a minor version bump instead of a major one was incorrect as the path to the contract has changed, and is in it of itself a breaking change. To illustrate, imagine a package that previously had:

```json
{
  "name": "foo",
  "version": "1.0.0",
  "dependencies": {
    "@gnosis.pm/owl-token": "^3.1.0"
  }
}
```

It would now start resolving to `3.2.0` (since `3.2.0 ∈ ^3.1.0` since `^3.1.0 = [3.1.0, 4.0.0)`). This would cause build errors since the `import` statements would no longer work. This would break any packages depending on `@gnosis.pm/owl-token` that did not use strict versioning (which I imagine is most, as `^version` is the default behaviour for `npm add --save` and `yarn add --save`).

2020-10-21 06:50 UTC, bh2smith commented
Yea @nlordell that's some great reasoning. I wish I had come up with this justification when I initially proposed a major version. I hadn't noticed at the time that all the import statements would need to be changed.

I will make the proposed version changes and update here before merging this.

2020-10-21 07:55 UTC, nlordell approved these changes
Looks good. Make sure to yank the [previous version](https://www.npmjs.com/package/@gnosis.pm/owl-token/v/3.2.0) as it can still cause unexpected breakage:
```
npm unpublish @gnosis.pm/owl-token@3.2.0
```

Note that (see [here](https://docs.npmjs.com/cli/unpublish)):
> unpublish is only allowed with versions published in the last 72 hours

2020-10-21 11:56 UTC, bh2smith commented
> Make sure to yank the previous version

Way ahead of you!

2020-10-21 11:57 UTC, bh2smith commented
@nlordell Look see

```sh
➜  owl-token git:(master) npm unpublish v3.2.0
npm ERR! Refusing to delete entire project.
npm ERR! Run with --force to do this.
npm ERR! 
npm ERR! npm unpublish [<@scope>/]<pkg>@<version>
npm ERR! npm unpublish [<@scope>/]<pkg> --force
➜  owl-token git:(master) npm unpublish v3.2.0 --force
npm WARN using --force I sure hope you know what you are doing.
- v3.2.0
```

2020-10-21 11:59 UTC, bh2smith commented
Weird... Now I tried again and seems to be a problem:


```sh
➜  owl-token git:(master) npm unpublish @gnosis.pm/owl-token@3.2.0
This operation requires a one-time password.
Enter OTP: 974223
npm ERR! code E405
npm ERR! 405 Method Not Allowed - PUT https://registry.npmjs.org/@gnosis.pm%2fowl-token/-rev/79-c7ef40a6fb97a85ba07b3284e091b8db - You can no longer unpublish this package.
npm ERR! Failed criteria: 
npm ERR! has dependent packages in the registry
npm ERR! 
npm ERR! Please deprecate it instead:
npm ERR! npm deprecate -f '@gnosis.pm/owl-token@3.2.0' "this package has been deprecated"
npm ERR! To learn more about our unpublish policies, see https://www.npmjs.com/policies/unpublish

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bensniff/.npm/_logs/2020-10-21T11_58_55_311Z-debug.log
```
Should I deprecate instead?

2020-10-21 12:01 UTC, merged

2020-10-21 12:06 UTC, nlordell commented
> Should I deprecate instead?

No.

I think you might have to contact NPM support :cry:

2020-10-21 12:12 UTC, bh2smith commented
I found it, this project had depended on it. https://github.com/gnosis/dex-liquidity-provision/pull/547