Event for trade volume calculation
gnosis/dex-contracts pull request #388
Opened 2019-12-10 09:16 UTC by josojo

Anxo noted in his review:
Listing trades: This queries would be basic usage of the exchange

And we discussed later on that we want to emit Events such that we can calculate the trading volume of each order.
I created this event, which contains the  batch index and the objective value. Hence, we can filter for the settlement events with the highest objective value per batchIndex and then easily calculate the trading volumes used for settling a batch

2019-12-10 13:26 UTC, fleupold reviewed
I think the plan was to create an event that can be indexed by user and orderId so that it can be easily queried. Can we emit a separate event for each execution and reversion of a trade?

cc @anxolin

2019-12-10 13:40 UTC, bh2smith commented
Is this related to #387 ?

2019-12-10 15:08 UTC, anxolin requested changes
Yes, exactly as Felix said.
Ideally, the point is being able to get the partial executions for a given order.  So indexed by owner and order Id. Also by batchId to be able to get any Trade by it's id

2019-12-10 16:29 UTC, fleupold approved these changes

2019-12-10 16:29 UTC, fleupold commented on contracts/BatchExchange.sol
> +    event TradeRevertion(address indexed owner, uint256 indexed orderIds, uint256 executedSellAmount, uint256 executedBuyAmount);
nit: naming TradeRever**s**ion

2019-12-10 16:53 UTC, merged

2019-12-11 10:58 UTC, anxolin commented
This one is my favourite of all the changes :) 
thanks

2019-12-11 11:01 UTC, anxolin commented
@josojo @fleupold I see you didn't add the batchId in the event. Was this a conscious decission?

2019-12-11 11:21 UTC, josojo commented
Yeah, it would be a lot of data duplication. 

From the time of the event, we can later easily determine the batchIndex. At least in dune, it was always very easy.
If you need it for the front-end let us know, then we will change it later

2019-12-11 12:32 UTC, anxolin commented
But if it is deterministic, why is in the `submitSolution`

Is the time of the event telling us deterministically the batchId?

2019-12-11 16:53 UTC, fleupold commented
> But if it is deterministic, why is in the submitSolution

In case you submitted a solution with a low gas price, it might be stuck in the tx queue for a while and only get executed once the batch it was valid for is already solved. 

In order to fail early (and not use more gas than necessary for a benign race condition) we ask the solver to specify which batch they were intending to solve and can fail early if this batch is no longer accepting solutions.

2019-12-11 17:24 UTC, anxolin commented
Okay, so you are saying, it's really 100% deterministic, this id is just as a fail early mechanism and we don't need to explicitly add it in the event.

If it's like that, it's fine for me, we can abstract this somehow in the libraries or when we index the event in the graph