Coherent naming batchId and batchIndex it, using uint32
gnosis/dex-contracts pull request #403
Opened 2019-12-16 12:26 UTC by josojo

2019-12-16 12:35 UTC, bh2smith approved these changes
Sweet!

2019-12-16 15:59 UTC, anxolin requested changes
But I thought it was the other way around. The good one is not `batchId`?

Note that also the getter is called `getBatchId()`

2019-12-16 16:51 UTC, fleupold commented
I slightly prefer batchIndex (but no strong feeling)

2019-12-17 09:57 UTC, josojo commented
@anxolin 
but it is not an Identifier, it is an index, as it is constantly increasing.

Would you be okay with it, once I change the getter to getBatchIndex as well?

2019-12-17 10:27 UTC, anxolin commented
Well, In reality I could argue it's an identifier, since it identifies an user order. I agree it's also an index (it's the implementation details)

It's like in a auto increment field in a database we call it "index" instead of "id" cause it's autoincremented and it's and index

Having said that, I don't care that much if we want to call it index or id.

2019-12-17 10:29 UTC, anxolin commented
What is more important for me is to be coherent, and write same concept always in the same way. Otherwise it's confusing I you see batchId, batchIndex, auctionNumber, auctionId, index, epoc,  etc..

2019-12-17 14:17 UTC, josojo commented
Anxo you are right.

`ID`  puts the emphasis that it is a unique identifier and `index` is a little bit more explicit on how it is used. 

I would also feel comfortable with both decisions. 
I changed the code to index for now. ( Here and in the other PR)

2019-12-17 15:03 UTC, bh2smith commented
I also prefer index since it could, technically, have started at zero (and IDs always start at 1).

2019-12-17 15:05 UTC, anxolin approved these changes
I approve cause I don't want to block this PR for this. But still like more `batchId` than `batchIndex` (on top of what I mentioned, it's shorter :) )

Also, changing to batchIndex affects more other modules since you are changing the interface, so that's more work

I think we should agree and try to do what's best here. We are reviewing specifically this in this PR, so I wouldn't do "batchIndex" for now and later we'll see. Now is the time to have consensus and leave it coherent

2019-12-17 16:10 UTC, fleupold commented
@anxolin I don't understand what you mean with the last two sentences you wrote. On the one hand you say you would change it later, on the other hand you say now is the time to make it coherent.

I wouldn't be too concerned about "breaking" contract changes at this point (e.g. the method rename). In fact, I'd say now is the time to do it - It won't get easier. 
It would be easier if all the code was in one repo, so all we'd have to do is a global "find-replace", instead of updating all our micro-repos with different PRs at different times.

2019-12-17 17:01 UTC, anxolin commented
@fleupold , sorry with last I tried to refer to Alex comment of:

> I changed the code to index for now

...but I think I wrote to fast, sorry for that. I was referring to his "for now". So I meant the opposite, we should do the change we believe is best now, instead of do something and later see

My vote is to call orderId and batchId, since they are used as identifiers, and it looks simpler to me. Besides, we already had this discussion and we agreed on id:
* https://github.com/gnosis/dex-contracts/pull/206
* https://github.com/gnosis/dex-contracts/pull/381

I approved the PR cause I don't find this discussion specifically important for me, so I'm ok if you all like calling it "index". I'll give us slight more work cause we need to apply the refactor in our code too though, so pls consider.

2019-12-18 09:33 UTC, nlordell commented
I think that we should just choose one and run with it and I don't think this is super important. That being said, I do agree with @anxolin and prefer `batchId` over `batchIndex` as I would argue that the `batchWhatever` is not an index and batches aren't indexable. Instead, it a derived value that uniquely identifies a given batch.
Personally I think that the best way to describe this is `batchNumber`.

2019-12-18 12:34 UTC, nlordell approved these changes

2019-12-18 16:05 UTC, bh2smith commented on contracts/EpochTokenLocker.sol
> -    mapping(address => mapping(address => uint256)) public lastCreditBatchId;
Nice catch!

2019-12-18 17:14 UTC, merged