Allow to unset withdrawBlockers in undoCurrentSolution
gnosis/dex-contracts pull request #421
Opened 2019-12-20 05:57 UTC by josojo

[Draft]

This PR enables a new solution submitter to undo all withdrawBlocks, which have been set by a previous solution.

2019-12-20 08:34 UTC, nlordell approved these changes

2019-12-20 08:56 UTC, fleupold approved these changes
I’m generally fine with this, but I’m not sure it’s worth it.
I think it would be worth mentioning the trade offs (extra gas) and what this achieves (attack that is possible in the current scenario). 

Also this is definitely something that needs to be flagged to the reviewers as adding last minute logic like this is a good candidate for bugs.

2019-12-20 08:56 UTC, fleupold commented on contracts/BatchExchange.sol
> +            address solutionSubmitter = latestSolution.solutionSubmitter;
For addition we have this logic exposed as it’s own method in the EpochTokenLocker (addBalanceAndDelayWithdraw). 

I think we should do the same for subtractions.

2019-12-20 08:56 UTC, fleupold commented on test/stablex/batch_exchange.js
> +    it("checks that withdraw blockers between solutions are reset", async () => {
This is really testing an implementation detail. I think instead we should test that you can withdraw your funds even if the token was traded on your behalf in the first solution of the test (of it was undone in the second solution).

2020-01-08 12:43 UTC, fleupold requested changes
Let's review this again after we combine subtractBalance and undoWithdrawBlock.

2020-01-13 14:32 UTC, josojo commented
We agreed that we will close this issue, as the attack for withdraw-locking is very very unlikely, and can always be prevented by canceling the orders.
Additionally, this new solution would increase the gas amount for submitting the non-first solution.

2020-01-13 14:32 UTC, closed without merging